before_install:
  - npm i -g https://github.com/IonicaBizau/gpm.git
  - gpm -n .. -t .. -u https -d 1 -i iso-test
  - gpm -n .. -t .. -u https -d 1 -i iso-assert
install:
  - npm i
matrix:
  include:
  - os: linux
    env: BROWSER=chromium-browser HEADLESS=1
    addons:
      apt:
        packages: chromium-browser
  - os: linux
    env: BROWSER=google-chrome-stable HEADLESS=1
    addons:
      chrome: "stable"
  - os: linux
    env: BROWSER=firefox MOZ_HEADLESS=1
    addons:
      firefox: "latest"
#  - os: osx
#    env: BROWSER=chromium-browser HEADLESS=1
#    addons:
#      homebrew:
#        casks: chromium
  - os: osx
    env: BROWSER=google-chrome-stable HEADLESS=1
    addons:
      chrome: "stable"
  - os: osx
    env: BROWSER=firefox MOZ_HEADLESS=1
    addons:
      firefox: "latest"
  - os: osx
    env: BROWSER=safari HEADLESS=1
    addons:
      homebrew:
        casks: safari

language: node_js
node_js:
  - "11"
